/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tokyo.northside.odapi.model.BilingualEntry;
import tokyo.northside.odapi.model.LexicalCategory;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Description of an entry for a particular part of speech
 */
@ApiModel(description = "Description of an entry for a particular part of speech")
@JsonPropertyOrder({
  BilingualLexicalEntry.JSON_PROPERTY_COMPOUNDS,
  BilingualLexicalEntry.JSON_PROPERTY_DERIVATIVE_OF,
  BilingualLexicalEntry.JSON_PROPERTY_DERIVATIVES,
  BilingualLexicalEntry.JSON_PROPERTY_ENTRIES,
  BilingualLexicalEntry.JSON_PROPERTY_GRAMMATICAL_FEATURES,
  BilingualLexicalEntry.JSON_PROPERTY_LANGUAGE,
  BilingualLexicalEntry.JSON_PROPERTY_LEXICAL_CATEGORY,
  BilingualLexicalEntry.JSON_PROPERTY_NOTES,
  BilingualLexicalEntry.JSON_PROPERTY_PHRASAL_VERBS,
  BilingualLexicalEntry.JSON_PROPERTY_PHRASES,
  BilingualLexicalEntry.JSON_PROPERTY_PRONUNCIATIONS,
  BilingualLexicalEntry.JSON_PROPERTY_ROOT,
  BilingualLexicalEntry.JSON_PROPERTY_TEXT,
  BilingualLexicalEntry.JSON_PROPERTY_VARIANT_FORMS
})
@JsonTypeName("BilingualLexicalEntry")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-27T22:47:07.450+09:00[Asia/Tokyo]")
public class BilingualLexicalEntry {
  public static final String JSON_PROPERTY_COMPOUNDS = "compounds";
  private List<Object> compounds = null;

  public static final String JSON_PROPERTY_DERIVATIVE_OF = "derivativeOf";
  private List<Object> derivativeOf = null;

  public static final String JSON_PROPERTY_DERIVATIVES = "derivatives";
  private List<Object> derivatives = null;

  public static final String JSON_PROPERTY_ENTRIES = "entries";
  private List<BilingualEntry> entries = null;

  public static final String JSON_PROPERTY_GRAMMATICAL_FEATURES = "grammaticalFeatures";
  private List<Object> grammaticalFeatures = null;

  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_LEXICAL_CATEGORY = "lexicalCategory";
  private LexicalCategory lexicalCategory;

  public static final String JSON_PROPERTY_NOTES = "notes";
  private List<Object> notes = null;

  public static final String JSON_PROPERTY_PHRASAL_VERBS = "phrasalVerbs";
  private List<Object> phrasalVerbs = null;

  public static final String JSON_PROPERTY_PHRASES = "phrases";
  private List<Object> phrases = null;

  public static final String JSON_PROPERTY_PRONUNCIATIONS = "pronunciations";
  private List<Object> pronunciations = null;

  public static final String JSON_PROPERTY_ROOT = "root";
  private String root;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public static final String JSON_PROPERTY_VARIANT_FORMS = "variantForms";
  private List<Object> variantForms = null;

  public BilingualLexicalEntry() { 
  }

  public BilingualLexicalEntry compounds(List<Object> compounds) {
    
    this.compounds = compounds;
    return this;
  }

  public BilingualLexicalEntry addCompoundsItem(Object compoundsItem) {
    if (this.compounds == null) {
      this.compounds = new ArrayList<>();
    }
    this.compounds.add(compoundsItem);
    return this;
  }

   /**
   * A list of written or spoken words
   * @return compounds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken words")
  @JsonProperty(JSON_PROPERTY_COMPOUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getCompounds() {
    return compounds;
  }


  @JsonProperty(JSON_PROPERTY_COMPOUNDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCompounds(List<Object> compounds) {
    this.compounds = compounds;
  }


  public BilingualLexicalEntry derivativeOf(List<Object> derivativeOf) {
    
    this.derivativeOf = derivativeOf;
    return this;
  }

  public BilingualLexicalEntry addDerivativeOfItem(Object derivativeOfItem) {
    if (this.derivativeOf == null) {
      this.derivativeOf = new ArrayList<>();
    }
    this.derivativeOf.add(derivativeOfItem);
    return this;
  }

   /**
   * A list of written or spoken words
   * @return derivativeOf
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken words")
  @JsonProperty(JSON_PROPERTY_DERIVATIVE_OF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getDerivativeOf() {
    return derivativeOf;
  }


  @JsonProperty(JSON_PROPERTY_DERIVATIVE_OF)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDerivativeOf(List<Object> derivativeOf) {
    this.derivativeOf = derivativeOf;
  }


  public BilingualLexicalEntry derivatives(List<Object> derivatives) {
    
    this.derivatives = derivatives;
    return this;
  }

  public BilingualLexicalEntry addDerivativesItem(Object derivativesItem) {
    if (this.derivatives == null) {
      this.derivatives = new ArrayList<>();
    }
    this.derivatives.add(derivativesItem);
    return this;
  }

   /**
   * A list of written or spoken words
   * @return derivatives
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken words")
  @JsonProperty(JSON_PROPERTY_DERIVATIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getDerivatives() {
    return derivatives;
  }


  @JsonProperty(JSON_PROPERTY_DERIVATIVES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDerivatives(List<Object> derivatives) {
    this.derivatives = derivatives;
  }


  public BilingualLexicalEntry entries(List<BilingualEntry> entries) {
    
    this.entries = entries;
    return this;
  }

  public BilingualLexicalEntry addEntriesItem(BilingualEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BilingualEntry> getEntries() {
    return entries;
  }


  @JsonProperty(JSON_PROPERTY_ENTRIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEntries(List<BilingualEntry> entries) {
    this.entries = entries;
  }


  public BilingualLexicalEntry grammaticalFeatures(List<Object> grammaticalFeatures) {
    
    this.grammaticalFeatures = grammaticalFeatures;
    return this;
  }

  public BilingualLexicalEntry addGrammaticalFeaturesItem(Object grammaticalFeaturesItem) {
    if (this.grammaticalFeatures == null) {
      this.grammaticalFeatures = new ArrayList<>();
    }
    this.grammaticalFeatures.add(grammaticalFeaturesItem);
    return this;
  }

   /**
   * The different forms are correlated with meanings or functions which we text as &#39;features&#39;
   * @return grammaticalFeatures
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The different forms are correlated with meanings or functions which we text as 'features'")
  @JsonProperty(JSON_PROPERTY_GRAMMATICAL_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getGrammaticalFeatures() {
    return grammaticalFeatures;
  }


  @JsonProperty(JSON_PROPERTY_GRAMMATICAL_FEATURES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrammaticalFeatures(List<Object> grammaticalFeatures) {
    this.grammaticalFeatures = grammaticalFeatures;
  }


  public BilingualLexicalEntry language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * IANA language code
   * @return language
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "IANA language code")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public BilingualLexicalEntry lexicalCategory(LexicalCategory lexicalCategory) {
    
    this.lexicalCategory = lexicalCategory;
    return this;
  }

   /**
   * Get lexicalCategory
   * @return lexicalCategory
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_LEXICAL_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public LexicalCategory getLexicalCategory() {
    return lexicalCategory;
  }


  @JsonProperty(JSON_PROPERTY_LEXICAL_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLexicalCategory(LexicalCategory lexicalCategory) {
    this.lexicalCategory = lexicalCategory;
  }


  public BilingualLexicalEntry notes(List<Object> notes) {
    
    this.notes = notes;
    return this;
  }

  public BilingualLexicalEntry addNotesItem(Object notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * various types of notes that appear
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "various types of notes that appear")
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getNotes() {
    return notes;
  }


  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotes(List<Object> notes) {
    this.notes = notes;
  }


  public BilingualLexicalEntry phrasalVerbs(List<Object> phrasalVerbs) {
    
    this.phrasalVerbs = phrasalVerbs;
    return this;
  }

  public BilingualLexicalEntry addPhrasalVerbsItem(Object phrasalVerbsItem) {
    if (this.phrasalVerbs == null) {
      this.phrasalVerbs = new ArrayList<>();
    }
    this.phrasalVerbs.add(phrasalVerbsItem);
    return this;
  }

   /**
   * A list of written or spoken words
   * @return phrasalVerbs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken words")
  @JsonProperty(JSON_PROPERTY_PHRASAL_VERBS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getPhrasalVerbs() {
    return phrasalVerbs;
  }


  @JsonProperty(JSON_PROPERTY_PHRASAL_VERBS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhrasalVerbs(List<Object> phrasalVerbs) {
    this.phrasalVerbs = phrasalVerbs;
  }


  public BilingualLexicalEntry phrases(List<Object> phrases) {
    
    this.phrases = phrases;
    return this;
  }

  public BilingualLexicalEntry addPhrasesItem(Object phrasesItem) {
    if (this.phrases == null) {
      this.phrases = new ArrayList<>();
    }
    this.phrases.add(phrasesItem);
    return this;
  }

   /**
   * A list of written or spoken words
   * @return phrases
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of written or spoken words")
  @JsonProperty(JSON_PROPERTY_PHRASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getPhrases() {
    return phrases;
  }


  @JsonProperty(JSON_PROPERTY_PHRASES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhrases(List<Object> phrases) {
    this.phrases = phrases;
  }


  public BilingualLexicalEntry pronunciations(List<Object> pronunciations) {
    
    this.pronunciations = pronunciations;
    return this;
  }

  public BilingualLexicalEntry addPronunciationsItem(Object pronunciationsItem) {
    if (this.pronunciations == null) {
      this.pronunciations = new ArrayList<>();
    }
    this.pronunciations.add(pronunciationsItem);
    return this;
  }

   /**
   * A list of possible pronunciations of a word
   * @return pronunciations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of possible pronunciations of a word")
  @JsonProperty(JSON_PROPERTY_PRONUNCIATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getPronunciations() {
    return pronunciations;
  }


  @JsonProperty(JSON_PROPERTY_PRONUNCIATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPronunciations(List<Object> pronunciations) {
    this.pronunciations = pronunciations;
  }


  public BilingualLexicalEntry root(String root) {
    
    this.root = root;
    return this;
  }

   /**
   * Abstract root form from which this lexicalEntry is derived.
   * @return root
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Abstract root form from which this lexicalEntry is derived.")
  @JsonProperty(JSON_PROPERTY_ROOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRoot() {
    return root;
  }


  @JsonProperty(JSON_PROPERTY_ROOT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoot(String root) {
    this.root = root;
  }


  public BilingualLexicalEntry text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * A given written or spoken realisation of an entry.
   * @return text
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "A given written or spoken realisation of an entry.")
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(String text) {
    this.text = text;
  }


  public BilingualLexicalEntry variantForms(List<Object> variantForms) {
    
    this.variantForms = variantForms;
    return this;
  }

  public BilingualLexicalEntry addVariantFormsItem(Object variantFormsItem) {
    if (this.variantForms == null) {
      this.variantForms = new ArrayList<>();
    }
    this.variantForms.add(variantFormsItem);
    return this;
  }

   /**
   * Various words that are used interchangeably depending on the context, e.g &#39;aluminium&#39; and &#39;aluminum&#39;
   * @return variantForms
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Various words that are used interchangeably depending on the context, e.g 'aluminium' and 'aluminum'")
  @JsonProperty(JSON_PROPERTY_VARIANT_FORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getVariantForms() {
    return variantForms;
  }


  @JsonProperty(JSON_PROPERTY_VARIANT_FORMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariantForms(List<Object> variantForms) {
    this.variantForms = variantForms;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BilingualLexicalEntry bilingualLexicalEntry = (BilingualLexicalEntry) o;
    return Objects.equals(this.compounds, bilingualLexicalEntry.compounds) &&
        Objects.equals(this.derivativeOf, bilingualLexicalEntry.derivativeOf) &&
        Objects.equals(this.derivatives, bilingualLexicalEntry.derivatives) &&
        Objects.equals(this.entries, bilingualLexicalEntry.entries) &&
        Objects.equals(this.grammaticalFeatures, bilingualLexicalEntry.grammaticalFeatures) &&
        Objects.equals(this.language, bilingualLexicalEntry.language) &&
        Objects.equals(this.lexicalCategory, bilingualLexicalEntry.lexicalCategory) &&
        Objects.equals(this.notes, bilingualLexicalEntry.notes) &&
        Objects.equals(this.phrasalVerbs, bilingualLexicalEntry.phrasalVerbs) &&
        Objects.equals(this.phrases, bilingualLexicalEntry.phrases) &&
        Objects.equals(this.pronunciations, bilingualLexicalEntry.pronunciations) &&
        Objects.equals(this.root, bilingualLexicalEntry.root) &&
        Objects.equals(this.text, bilingualLexicalEntry.text) &&
        Objects.equals(this.variantForms, bilingualLexicalEntry.variantForms);
  }

  @Override
  public int hashCode() {
    return Objects.hash(compounds, derivativeOf, derivatives, entries, grammaticalFeatures, language, lexicalCategory, notes, phrasalVerbs, phrases, pronunciations, root, text, variantForms);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BilingualLexicalEntry {\n");
    sb.append("    compounds: ").append(toIndentedString(compounds)).append("\n");
    sb.append("    derivativeOf: ").append(toIndentedString(derivativeOf)).append("\n");
    sb.append("    derivatives: ").append(toIndentedString(derivatives)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    grammaticalFeatures: ").append(toIndentedString(grammaticalFeatures)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    lexicalCategory: ").append(toIndentedString(lexicalCategory)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    phrasalVerbs: ").append(toIndentedString(phrasalVerbs)).append("\n");
    sb.append("    phrases: ").append(toIndentedString(phrases)).append("\n");
    sb.append("    pronunciations: ").append(toIndentedString(pronunciations)).append("\n");
    sb.append("    root: ").append(toIndentedString(root)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("    variantForms: ").append(toIndentedString(variantForms)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

