/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tokyo.northside.odapi.model.DomainsList;
import tokyo.northside.odapi.model.RegionsList;
import tokyo.northside.odapi.model.RegistersList;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SenseConstructions
 */
@JsonPropertyOrder({
  SenseConstructions.JSON_PROPERTY_DOMAINS,
  SenseConstructions.JSON_PROPERTY_EXAMPLES,
  SenseConstructions.JSON_PROPERTY_NOTES,
  SenseConstructions.JSON_PROPERTY_REGIONS,
  SenseConstructions.JSON_PROPERTY_REGISTERS,
  SenseConstructions.JSON_PROPERTY_TEXT
})
@JsonTypeName("Sense_constructions")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-27T22:47:07.450+09:00[Asia/Tokyo]")
public class SenseConstructions {
  public static final String JSON_PROPERTY_DOMAINS = "domains";
  private DomainsList domains;

  public static final String JSON_PROPERTY_EXAMPLES = "examples";
  private List<List<String>> examples = null;

  public static final String JSON_PROPERTY_NOTES = "notes";
  private List<Object> notes = null;

  public static final String JSON_PROPERTY_REGIONS = "regions";
  private RegionsList regions;

  public static final String JSON_PROPERTY_REGISTERS = "registers";
  private RegistersList registers;

  public static final String JSON_PROPERTY_TEXT = "text";
  private String text;

  public SenseConstructions() { 
  }

  public SenseConstructions domains(DomainsList domains) {
    
    this.domains = domains;
    return this;
  }

   /**
   * Get domains
   * @return domains
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DomainsList getDomains() {
    return domains;
  }


  @JsonProperty(JSON_PROPERTY_DOMAINS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDomains(DomainsList domains) {
    this.domains = domains;
  }


  public SenseConstructions examples(List<List<String>> examples) {
    
    this.examples = examples;
    return this;
  }

  public SenseConstructions addExamplesItem(List<String> examplesItem) {
    if (this.examples == null) {
      this.examples = new ArrayList<>();
    }
    this.examples.add(examplesItem);
    return this;
  }

   /**
   * Get examples
   * @return examples
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_EXAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<List<String>> getExamples() {
    return examples;
  }


  @JsonProperty(JSON_PROPERTY_EXAMPLES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExamples(List<List<String>> examples) {
    this.examples = examples;
  }


  public SenseConstructions notes(List<Object> notes) {
    
    this.notes = notes;
    return this;
  }

  public SenseConstructions addNotesItem(Object notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * various types of notes that appear
   * @return notes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "various types of notes that appear")
  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Object> getNotes() {
    return notes;
  }


  @JsonProperty(JSON_PROPERTY_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNotes(List<Object> notes) {
    this.notes = notes;
  }


  public SenseConstructions regions(RegionsList regions) {
    
    this.regions = regions;
    return this;
  }

   /**
   * Get regions
   * @return regions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REGIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegionsList getRegions() {
    return regions;
  }


  @JsonProperty(JSON_PROPERTY_REGIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegions(RegionsList regions) {
    this.regions = regions;
  }


  public SenseConstructions registers(RegistersList registers) {
    
    this.registers = registers;
    return this;
  }

   /**
   * Get registers
   * @return registers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_REGISTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RegistersList getRegisters() {
    return registers;
  }


  @JsonProperty(JSON_PROPERTY_REGISTERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRegisters(RegistersList registers) {
    this.registers = registers;
  }


  public SenseConstructions text(String text) {
    
    this.text = text;
    return this;
  }

   /**
   * The construction text
   * @return text
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The construction text")
  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getText() {
    return text;
  }


  @JsonProperty(JSON_PROPERTY_TEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setText(String text) {
    this.text = text;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SenseConstructions senseConstructions = (SenseConstructions) o;
    return Objects.equals(this.domains, senseConstructions.domains) &&
        Objects.equals(this.examples, senseConstructions.examples) &&
        Objects.equals(this.notes, senseConstructions.notes) &&
        Objects.equals(this.regions, senseConstructions.regions) &&
        Objects.equals(this.registers, senseConstructions.registers) &&
        Objects.equals(this.text, senseConstructions.text);
  }

  @Override
  public int hashCode() {
    return Objects.hash(domains, examples, notes, regions, registers, text);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SenseConstructions {\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    regions: ").append(toIndentedString(regions)).append("\n");
    sb.append("    registers: ").append(toIndentedString(registers)).append("\n");
    sb.append("    text: ").append(toIndentedString(text)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

