/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.v2;

import tokyo.northside.odapi.ApiException;
import tokyo.northside.odapi.model.ErrorSchema;
import tokyo.northside.odapi.model.Inflections;
import org.junit.Test;
import org.junit.Ignore;
import org.junit.Assert;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for InflectionsApi
 */
@Ignore
public class InflectionsApiTest {

    private final InflectionsApi api = new InflectionsApi();

    /**
     * Retrieves the inflected forms of a given word.
     *
     * Retrieve all the [inflections](documentation/glossary?term&#x3D;inflection) of a given word_id. The inflections are given for a lexicalEntry with a specific lexicalCategory. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void inflectionsSourceLangWordIdGetTest() throws ApiException {
        String sourceLang = null;
        String wordId = null;
        String appId = null;
        String appKey = null;
        Boolean strictMatch = null;
        Inflections response = api.inflectionsSourceLangWordIdGet(sourceLang, wordId, appId, appKey, strictMatch);

        // TODO: test validations
    }
}
