/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InflectedForm;
import org.openapitools.client.model.Sense;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Entry
 */
public class EntryTest {
    private final Entry model = new Entry();

    /**
     * Model tests for Entry
     */
    @Test
    public void testEntry() {
        // TODO: test Entry
    }

    /**
     * Test the property 'crossReferenceMarkers'
     */
    @Test
    public void crossReferenceMarkersTest() {
        // TODO: test crossReferenceMarkers
    }

    /**
     * Test the property 'crossReferences'
     */
    @Test
    public void crossReferencesTest() {
        // TODO: test crossReferences
    }

    /**
     * Test the property 'etymologies'
     */
    @Test
    public void etymologiesTest() {
        // TODO: test etymologies
    }

    /**
     * Test the property 'grammaticalFeatures'
     */
    @Test
    public void grammaticalFeaturesTest() {
        // TODO: test grammaticalFeatures
    }

    /**
     * Test the property 'homographNumber'
     */
    @Test
    public void homographNumberTest() {
        // TODO: test homographNumber
    }

    /**
     * Test the property 'inflections'
     */
    @Test
    public void inflectionsTest() {
        // TODO: test inflections
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'pronunciations'
     */
    @Test
    public void pronunciationsTest() {
        // TODO: test pronunciations
    }

    /**
     * Test the property 'senses'
     */
    @Test
    public void sensesTest() {
        // TODO: test senses
    }

    /**
     * Test the property 'variantForms'
     */
    @Test
    public void variantFormsTest() {
        // TODO: test variantForms
    }

}
