/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LexicalEntry;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HeadwordEntry
 */
public class HeadwordEntryTest {
    private final HeadwordEntry model = new HeadwordEntry();

    /**
     * Model tests for HeadwordEntry
     */
    @Test
    public void testHeadwordEntry() {
        // TODO: test HeadwordEntry
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'lexicalEntries'
     */
    @Test
    public void lexicalEntriesTest() {
        // TODO: test lexicalEntries
    }

    /**
     * Test the property 'pronunciations'
     */
    @Test
    public void pronunciationsTest() {
        // TODO: test pronunciations
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'word'
     */
    @Test
    public void wordTest() {
        // TODO: test word
    }

}
