/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.InflectedForm;
import org.openapitools.client.model.LexicalCategory;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InflectionLexicalEntry
 */
public class InflectionLexicalEntryTest {
    private final InflectionLexicalEntry model = new InflectionLexicalEntry();

    /**
     * Model tests for InflectionLexicalEntry
     */
    @Test
    public void testInflectionLexicalEntry() {
        // TODO: test InflectionLexicalEntry
    }

    /**
     * Test the property 'grammaticalFeatures'
     */
    @Test
    public void grammaticalFeaturesTest() {
        // TODO: test grammaticalFeatures
    }

    /**
     * Test the property 'inflections'
     */
    @Test
    public void inflectionsTest() {
        // TODO: test inflections
    }

    /**
     * Test the property 'language'
     */
    @Test
    public void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'lexicalCategory'
     */
    @Test
    public void lexicalCategoryTest() {
        // TODO: test lexicalCategory
    }

}
