/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SenseLink
 */
public class SenseLinkTest {
    private final SenseLink model = new SenseLink();

    /**
     * Model tests for SenseLink
     */
    @Test
    public void testSenseLink() {
        // TODO: test SenseLink
    }

    /**
     * Test the property 'entryId'
     */
    @Test
    public void entryIdTest() {
        // TODO: test entryId
    }

    /**
     * Test the property 'senseId'
     */
    @Test
    public void senseIdTest() {
        // TODO: test senseId
    }

}
