/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UtilityLabelsResults
 */
public class UtilityLabelsResultsTest {
    private final UtilityLabelsResults model = new UtilityLabelsResults();

    /**
     * Model tests for UtilityLabelsResults
     */
    @Test
    public void testUtilityLabelsResults() {
        // TODO: test UtilityLabelsResults
    }

    /**
     * Test the property 'en'
     */
    @Test
    public void enTest() {
        // TODO: test en
    }

}
