/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for WordlistResults
 */
public class WordlistResultsTest {
    private final WordlistResults model = new WordlistResults();

    /**
     * Model tests for WordlistResults
     */
    @Test
    public void testWordlistResults() {
        // TODO: test WordlistResults
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'matchString'
     */
    @Test
    public void matchStringTest() {
        // TODO: test matchString
    }

    /**
     * Test the property 'matchType'
     */
    @Test
    public void matchTypeTest() {
        // TODO: test matchType
    }

    /**
     * Test the property 'region'
     */
    @Test
    public void regionTest() {
        // TODO: test region
    }

    /**
     * Test the property 'word'
     */
    @Test
    public void wordTest() {
        // TODO: test word
    }

}
