/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.SenseLink;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Link to a specific sense of an entry in another dictionary
 */
@ApiModel(description = "Link to a specific sense of an entry in another dictionary")
@JsonPropertyOrder({
  DatasetCrossLink.JSON_PROPERTY_LANGUAGE,
  DatasetCrossLink.JSON_PROPERTY_ENTRY_ID,
  DatasetCrossLink.JSON_PROPERTY_SENSE_ID
})
@JsonTypeName("DatasetCrossLink")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-27T11:23:50.379+09:00[Asia/Tokyo]")
public class DatasetCrossLink {
  public static final String JSON_PROPERTY_LANGUAGE = "language";
  private String language;

  public static final String JSON_PROPERTY_ENTRY_ID = "entry_id";
  private String entryId;

  public static final String JSON_PROPERTY_SENSE_ID = "sense_id";
  private String senseId;

  public DatasetCrossLink() { 
  }

  public DatasetCrossLink language(String language) {
    
    this.language = language;
    return this;
  }

   /**
   * language of the dictionary where the linked sense can be found
   * @return language
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "language of the dictionary where the linked sense can be found")
  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLanguage() {
    return language;
  }


  @JsonProperty(JSON_PROPERTY_LANGUAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLanguage(String language) {
    this.language = language;
  }


  public DatasetCrossLink entryId(String entryId) {
    
    this.entryId = entryId;
    return this;
  }

   /**
   * identifier of a word
   * @return entryId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "identifier of a word")
  @JsonProperty(JSON_PROPERTY_ENTRY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntryId() {
    return entryId;
  }


  @JsonProperty(JSON_PROPERTY_ENTRY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntryId(String entryId) {
    this.entryId = entryId;
  }


  public DatasetCrossLink senseId(String senseId) {
    
    this.senseId = senseId;
    return this;
  }

   /**
   * identifier of a sense
   * @return senseId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "identifier of a sense")
  @JsonProperty(JSON_PROPERTY_SENSE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSenseId() {
    return senseId;
  }


  @JsonProperty(JSON_PROPERTY_SENSE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSenseId(String senseId) {
    this.senseId = senseId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetCrossLink datasetCrossLink = (DatasetCrossLink) o;
    return Objects.equals(this.language, datasetCrossLink.language) &&
        Objects.equals(this.entryId, datasetCrossLink.entryId) &&
        Objects.equals(this.senseId, datasetCrossLink.senseId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(language, entryId, senseId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetCrossLink {\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    entryId: ").append(toIndentedString(entryId)).append("\n");
    sb.append("    senseId: ").append(toIndentedString(senseId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

