/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * A mapping of filters available per endpoints.
 */
@ApiModel(description = "A mapping of filters available per endpoints.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-12-26T13:13:15.302+09:00[Asia/Tokyo]")
public class FiltersResults {
  public static final String SERIALIZED_NAME_ENTRIES = "entries";
  @SerializedName(SERIALIZED_NAME_ENTRIES)
  private List<String> entries = null;

  public static final String SERIALIZED_NAME_LEMMAS = "lemmas";
  @SerializedName(SERIALIZED_NAME_LEMMAS)
  private List<String> lemmas = null;

  public static final String SERIALIZED_NAME_SENTENCES = "sentences";
  @SerializedName(SERIALIZED_NAME_SENTENCES)
  private List<String> sentences = null;

  public static final String SERIALIZED_NAME_THESAURUS = "thesaurus";
  @SerializedName(SERIALIZED_NAME_THESAURUS)
  private List<String> thesaurus = null;

  public static final String SERIALIZED_NAME_TRANSLATIONS = "translations";
  @SerializedName(SERIALIZED_NAME_TRANSLATIONS)
  private List<String> translations = null;

  public FiltersResults() { 
  }

  public FiltersResults entries(List<String> entries) {
    
    this.entries = entries;
    return this;
  }

  public FiltersResults addEntriesItem(String entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<String>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getEntries() {
    return entries;
  }


  public void setEntries(List<String> entries) {
    this.entries = entries;
  }


  public FiltersResults lemmas(List<String> lemmas) {
    
    this.lemmas = lemmas;
    return this;
  }

  public FiltersResults addLemmasItem(String lemmasItem) {
    if (this.lemmas == null) {
      this.lemmas = new ArrayList<String>();
    }
    this.lemmas.add(lemmasItem);
    return this;
  }

   /**
   * Get lemmas
   * @return lemmas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getLemmas() {
    return lemmas;
  }


  public void setLemmas(List<String> lemmas) {
    this.lemmas = lemmas;
  }


  public FiltersResults sentences(List<String> sentences) {
    
    this.sentences = sentences;
    return this;
  }

  public FiltersResults addSentencesItem(String sentencesItem) {
    if (this.sentences == null) {
      this.sentences = new ArrayList<String>();
    }
    this.sentences.add(sentencesItem);
    return this;
  }

   /**
   * Get sentences
   * @return sentences
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getSentences() {
    return sentences;
  }


  public void setSentences(List<String> sentences) {
    this.sentences = sentences;
  }


  public FiltersResults thesaurus(List<String> thesaurus) {
    
    this.thesaurus = thesaurus;
    return this;
  }

  public FiltersResults addThesaurusItem(String thesaurusItem) {
    if (this.thesaurus == null) {
      this.thesaurus = new ArrayList<String>();
    }
    this.thesaurus.add(thesaurusItem);
    return this;
  }

   /**
   * Get thesaurus
   * @return thesaurus
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getThesaurus() {
    return thesaurus;
  }


  public void setThesaurus(List<String> thesaurus) {
    this.thesaurus = thesaurus;
  }


  public FiltersResults translations(List<String> translations) {
    
    this.translations = translations;
    return this;
  }

  public FiltersResults addTranslationsItem(String translationsItem) {
    if (this.translations == null) {
      this.translations = new ArrayList<String>();
    }
    this.translations.add(translationsItem);
    return this;
  }

   /**
   * Get translations
   * @return translations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTranslations() {
    return translations;
  }


  public void setTranslations(List<String> translations) {
    this.translations = translations;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FiltersResults filtersResults = (FiltersResults) o;
    return Objects.equals(this.entries, filtersResults.entries) &&
        Objects.equals(this.lemmas, filtersResults.lemmas) &&
        Objects.equals(this.sentences, filtersResults.sentences) &&
        Objects.equals(this.thesaurus, filtersResults.thesaurus) &&
        Objects.equals(this.translations, filtersResults.translations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, lemmas, sentences, thesaurus, translations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FiltersResults {\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    lemmas: ").append(toIndentedString(lemmas)).append("\n");
    sb.append("    sentences: ").append(toIndentedString(sentences)).append("\n");
    sb.append("    thesaurus: ").append(toIndentedString(thesaurus)).append("\n");
    sb.append("    translations: ").append(toIndentedString(translations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

