/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.model;

import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DomainsList
 */
public class DomainsListTest {
    private final DomainsList model = new DomainsList();

    /**
     * Model tests for DomainsList
     */
    @Test
    public void testDomainsList() {
        // TODO: test DomainsList
    }

}
