/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FiltersResults
 */
public class FiltersResultsTest {
    private final FiltersResults model = new FiltersResults();

    /**
     * Model tests for FiltersResults
     */
    @Test
    public void testFiltersResults() {
        // TODO: test FiltersResults
    }

    /**
     * Test the property 'entries'
     */
    @Test
    public void entriesTest() {
        // TODO: test entries
    }

    /**
     * Test the property 'lemmas'
     */
    @Test
    public void lemmasTest() {
        // TODO: test lemmas
    }

    /**
     * Test the property 'sentences'
     */
    @Test
    public void sentencesTest() {
        // TODO: test sentences
    }

    /**
     * Test the property 'thesaurus'
     */
    @Test
    public void thesaurusTest() {
        // TODO: test thesaurus
    }

    /**
     * Test the property 'translations'
     */
    @Test
    public void translationsTest() {
        // TODO: test translations
    }

}
