/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package tokyo.northside.odapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import tokyo.northside.odapi.model.DomainClassesList;
import tokyo.northside.odapi.model.DomainsList;
import tokyo.northside.odapi.model.RegionsList;
import tokyo.northside.odapi.model.RegistersList;
import tokyo.northside.odapi.model.SemanticClassesList;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ThesaurusSense
 */
public class ThesaurusSenseTest {
    private final ThesaurusSense model = new ThesaurusSense();

    /**
     * Model tests for ThesaurusSense
     */
    @Test
    public void testThesaurusSense() {
        // TODO: test ThesaurusSense
    }

    /**
     * Test the property 'antonyms'
     */
    @Test
    public void antonymsTest() {
        // TODO: test antonyms
    }

    /**
     * Test the property 'domainClasses'
     */
    @Test
    public void domainClassesTest() {
        // TODO: test domainClasses
    }

    /**
     * Test the property 'domains'
     */
    @Test
    public void domainsTest() {
        // TODO: test domains
    }

    /**
     * Test the property 'examples'
     */
    @Test
    public void examplesTest() {
        // TODO: test examples
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'regions'
     */
    @Test
    public void regionsTest() {
        // TODO: test regions
    }

    /**
     * Test the property 'registers'
     */
    @Test
    public void registersTest() {
        // TODO: test registers
    }

    /**
     * Test the property 'semanticClasses'
     */
    @Test
    public void semanticClassesTest() {
        // TODO: test semanticClasses
    }

    /**
     * Test the property 'subsenses'
     */
    @Test
    public void subsensesTest() {
        // TODO: test subsenses
    }

    /**
     * Test the property 'synonyms'
     */
    @Test
    public void synonymsTest() {
        // TODO: test synonyms
    }

}
